version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    ports:
      - "80:80"
    command: nginx -g 'daemon off;'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
